#!/bin/bash
#original
#ffmpeg -i input.mkv -filter_complex "[0:a]silencedetect=n=-90dB:d=0.3[outa]" -map [outa] -f s16le -y /dev/null |& F='-aq 70 -v warning' perl -ne 'INIT { $ss=0; $se=0; } if (/silence_start: (\S+)/) { $ss=$1; $ctr+=1; printf "ffmpeg -nostdin -i input.mkv -ss %f -t %f $ENV{F} -y %03d.mkv\n", $se, ($ss-$se), $ctr; } if (/silence_end: (\S+)/) { $se=$1; } END { printf "ffmpeg -nostdin -i input.mkv -ss %f $ENV{F} -y %03d.mkv\n", $se, $ctr+1; }' | bash -x
#for youtube-dl --exec
#ffmpeg -i {} -filter_complex "[0:a]silencedetect=n=-48dB:d=0.5[outa]" -map [outa] -f s16le -y /dev/null |& F='-aq 70 -v warning' perl -ne 'INIT { $ss=0; $se=0; } if (/silence_start: (\S+)/) { $ss=$1; $ctr+=1; printf "ffmpeg -nostdin -i {} -ss %f -t %f $ENV{F} -y %03d{}.mkv\n", $se, ($ss-$se), $ctr; } if (/silence_end: (\S+)/) { $se=$1; } END { printf "ffmpeg -nostdin -i {} -ss %f $ENV{F} -y %03d{}.mkv\n", $se, $ctr+1; }' | bash -x
#merge with youtube-dl
#youtube-dl -f bestaudio[ext=m4a] -o "%(playlist_index)s-%(playlist)s-(%(uploader)s)-[%(id)s].%(ext)s" --exec "ffmpeg -i {} -filter_complex "[0:a]silencedetect=n=-48dB:d=0.5[outa]" -map [outa] -f s16le -y /dev/null |& F='-aq 70 -v warning' perl -ne 'INIT { $ss=0; $se=0; } if (/silence_start: (\S+)/) { $ss=$1; $ctr+=1; printf "ffmpeg -nostdin -i {} -ss %f -t %f $ENV{F} -y %03d{}.mkv\n", $se, ($ss-$se), $ctr; } if (/silence_end: (\S+)/) { $se=$1; } END { printf "ffmpeg -nostdin -i {} -ss %f $ENV{F} -y %03d{}.mkv\n", $se, $ctr+1; }' | bash -x" "https://www.youtube.com/watch?v=U4lk-PHI3uI&list=PLK9HTVqTYaTG75y3al1WEI75z2ZXClJEK"
#youtube-dl -f bestaudio[ext=m4a] -o "%(playlist_index)s-%(playlist)s-(%(uploader)s)-[%(id)s].%(ext)s" --exec "ffmpeg -i {} -filter_complex \"[0:a]silencedetect=n=-48dB:d=0.5[outa]\" -map [outa] -f s16le -y /dev/null |& F=\'-aq 70 -v warning\' perl -ne \'INIT { $ss=0; $se=0; } if (/silence_start: (\S+)/) { $ss=$1; $ctr+=1; printf \"ffmpeg -nostdin -i {} -ss %f -t %f $ENV{F} -y %03d{}.mkv\n\", $se, ($ss-$se), $ctr; } if (/silence_end: (\S+)/) { $se=$1; } END { printf \"ffmpeg -nostdin -i {} -ss %f $ENV{F} -y %03d{}.mkv\n\", $se, $ctr+1; }\' | bash -x" "https://www.youtube.com/watch?v=U4lk-PHI3uI&list=PLK9HTVqTYaTG75y3al1WEI75z2ZXClJEK"
#youtube-dl -f bestaudio[ext=m4a] --ignore-config -o "%(playlist_index)s-%(playlist)s-(%(uploader)s)-[%(id)s].%(ext)s" --exec "ffmpeg -i {} -filter_complex \"[0:a]silencedetect=n=-48dB:d=0.5[outa]\" -map [outa] -f s16le -y /dev/null 2>&1 | F='-aq 70 -v warning' perl -ne 'INIT { $ss=0; $se=0; } if (/silence_start: (\S+)/) { $ss=$1; $ctr+=1; printf \"ffmpeg -nostdin -i {} -ss %f -t %f $ENV{F} -y %03d{}.mkv\n\", $se, ($ss-$se), $ctr; } if (/silence_end: (\S+)/) { $se=$1; } END { printf \"ffmpeg -nostdin -i {} -ss %f $ENV{F} -y %03d{}.mkv\n\", $se, $ctr+1; }' | bash -x" "https://www.youtube.com/watch?v=U4lk-PHI3uI&list=PLK9HTVqTYaTG75y3al1WEI75z2ZXClJEK"
#youtube-dl -f bestaudio[ext=m4a] --ignore-config -o "%(playlist_index)s-%(playlist)s-(%(uploader)s)-[%(id)s].%(ext)s" --exec "ffmpeg -i {} -filter_complex \"[0:a]silencedetect=n=-48dB:d=0.5[outa]\" -map [outa] -f s16le -y /dev/null 2>&1 | perl -ne 'INIT { $ss=0; $se=0; } if (/silence_start: (\S+)/) { $ss=$1; $ctr+=1; printf \"ffmpeg -nostdin -i {} -ss %f -t %f $ENV{'-aq 70 -v warning'} -y %03d{}.mkv\n\", $se, ($ss-$se), $ctr; } if (/silence_end: (\S+)/) { $se=$1; } END { printf \"ffmpeg -nostdin -i {} -ss %f $ENV{'-aq 70 -v warning'} -y %03d{}.mkv\n\", $se, $ctr+1; }' | bash -x" "https://www.youtube.com/watch?v=U4lk-PHI3uI&list=PLK9HTVqTYaTG75y3al1WEI75z2ZXClJEK"
#youtube-dl -f bestaudio[ext=m4a] -o "%(playlist_index)s-%(playlist)s-(%(uploader)s)-[%(id)s].%(ext)s" --ignore-config --exec "ffmpeg -i {} -filter_complex \"[0:a]silencedetect=n=-48dB:d=0.3[outa]\" -map [outa] -f s16le -y /dev/null 2>&1 | perl -ne 'INIT { $ss=0; $se=0; } if (/silence_start: (\S+)/) { $ss=$1; $ctr+=1; printf \"ffmpeg -nostdin -i {} -ss %f -t %f $ENV{F} -y %03d.m4a\n\", $se, ($ss-$se), $ctr; } if (/silence_end: (\S+)/) { $se=$1; } END { printf \"ffmpeg -nostdin -i {} -ss %f $ENV{F} -y %03d.m4a\n\", $se, $ctr+1; }' | bash -x" "https://www.youtube.com/watch?v=U4lk-PHI3uI&list=PLK9HTVqTYaTG75y3al1WEI75z2ZXClJEK"
#ffmpeg -i 1.m4a -filter_complex "[0:a]silencedetect=n=-48dB:d=0.5[outa]" -map [outa] -f s16le -y /dev/null |& F='-aq 70 -v warning' perl -ne 'INIT { $ss=0; $se=0; } if (/silence_start: (\S+)/) { $ss=$1; $ctr+=1; printf "ffmpeg -nostdin -i 1.m4a -ss %f -t %f $ENV{F} -y %03d.m4a\n", $se, ($ss-$se), $ctr; } if (/silence_end: (\S+)/) { $se=$1; } END { printf "ffmpeg -nostdin -i 1.m4a -ss %f $ENV{F} -y %03d.m4a\n", $se, $ctr+1; }' | bash -x
youtube-dl -f bestaudio[ext=m4a] -o "%(playlist_index)s-%(id)s.%(ext)s" --ignore-config --exec "ffmpeg -i {} -filter_complex \"[0:a]silencedetect=n=-48dB:d=0.5[outa]\" -map [outa] -f s16le -y /dev/null |& F='-aq 70 -v warning' perl -ne 'INIT { \$ss=0; \$se=0; } if (/silence_start: (\S+)/) { \$ss=\$1; \$ctr+=1; printf \"ffmpeg -nostdin -i {} -ss %f -t %f \$ENV{F} -y %03d.m4a\n\", \$se, (\$ss-\$se), \$ctr; } if (/silence_end: (\S+)/) { \$se=\$1; } END { printf \"ffmpeg -nostdin -i {} -ss %f \$ENV{F} -y %03d.m4a\n\", \$se, \$ctr+1; }' | bash -x" "https://www.youtube.com/watch?v=U4lk-PHI3uI&list=PLK9HTVqTYaTG75y3al1WEI75z2ZXClJEK"
